apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-b-deployment
  labels:
    app: web-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-b
  template:
    metadata:
      labels:
        app: web-b
    spec:
      containers:
      - name: web-b
        image: yxyj1919/ingress-demo-b
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-b
  name: web-b-svc
spec:
  selector:
    app: web-b
  ports:
    - name: http
      protocol: TCP
      port: 80
  sessionAffinity: None
  type: ClusterIP
